name: Angular CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24]

    steps:

      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar Linter
        run: npm run lint

      - name: Ejecutar pruebas
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Generar build
        run: npm run build -- --configuration production

      - name: Subir artefactos
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist/